service: sls-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ap-southeast-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
