service: sls-backend
frameworkVersion: '3'

provider:
  name: aws
  deploymentMethod: direct
  runtime: nodejs18.x
  stage: alpha
  region: ap-southeast-1
  memorySize: 256

functions:
  proxy:
    handler: index.handler
    name: ${sls:stage}-proxyAi
    description: API proxy for openai functions
    timeout: 45
    environment: 
      OPENAI_API_KEY: ${ssm:/openai-key}
    events:
      - httpApi: '*'

plugins:
  - serverless-offline
custom:
  serverless-offline:
    httpPort: 4000