service: aws-node-express-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-west-2

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
